import React, { Component, useState, useEffect, useReducer, useRef, useMemo } from 'react';
import { SideMenu } from './components/SideMenu';
import { 
    CustomMenuIcon, IconPlus, IconMinus, IconTrash, IconUndo, IconSearch, IconCamera, IconGallery, IconClipboard, IconX, IconShare, IconChevronLeft, IconChevronRight,
    IconFileWord, IconFileExcel, IconWhatsapp, IconTelegram, IconEmail, IconSave
} from './components/icons';
import { EquipmentCategory, AppData, DailyData, EquipmentItem } from './types';
import { CATEGORIES } from './constants';

// --- UTILITIES ---

const getFormattedDate = (date: Date): string => {
  return date.toISOString().split('T')[0];
};

const generateId = () => {
  return Date.now().toString(36) + Math.random().toString(36).substring(2);
};

const createEmptyDailyData = (): DailyData => {
  const data = CATEGORIES.reduce((acc, category) => {
    acc[category] = [];
    return acc;
  }, {} as DailyData);

  CATEGORIES.forEach(category => {
    data[category].push({ id: generateId(), qt: '', contract: '', serial: '', photos: [] });
  });

  return data;
};

// Helper to get data for a range (Day or Month-to-Date)
const getDataInRange = (appData: AppData, currentDate: Date, scope: 'day' | 'month'): { data: DailyData, label: string } => {
    const fmtDate = getFormattedDate(currentDate);
    
    if (scope === 'day') {
        return { 
            data: appData[fmtDate] || createEmptyDailyData(), 
            label: fmtDate 
        };
    } else {
        // Month scope: From 1st of month to current selected date
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();
        const startDay = 1;
        const currentDay = currentDate.getDate();
        
        const aggregatedData = createEmptyDailyData();
        // Clear the default empty rows generated by createEmptyDailyData so we only have real data
        CATEGORIES.forEach(cat => aggregatedData[cat] = []);

        for (let d = startDay; d <= currentDay; d++) {
            const loopDate = new Date(year, month, d);
            const loopFmt = getFormattedDate(loopDate);
            const dayData = appData[loopFmt];

            if (dayData) {
                CATEGORIES.forEach(cat => {
                    const items = dayData[cat] || [];
                    // Only add active items
                    const activeItems = items.filter(isItemActive);
                    if (activeItems.length > 0) {
                        // We clone to avoid ref issues, and maybe append date to ID to ensure uniqueness in list
                        aggregatedData[cat].push(...activeItems);
                    }
                });
            }
        }
        return { 
            data: aggregatedData, 
            label: `Mês ${month + 1}/${year} (até dia ${currentDay})` 
        };
    }
};

// --- REDUCER ---

type Action =
  | { type: 'SET_DATA'; payload: AppData }
  | { type: 'ENSURE_DAY_DATA'; payload: { date: string; dayData: DailyData } }
  | { type: 'ADD_ITEM'; payload: { date: string; category: EquipmentCategory } }
  | { type: 'UPDATE_ITEM'; payload: { date: string; category: EquipmentCategory; item: EquipmentItem } }
  | { type: 'DELETE_ITEMS'; payload: { date: string; category: EquipmentCategory; itemIds: string[] } }
  | { type: 'CLEAR_ALL_DATA' };

const dataReducer = (state: AppData, action: Action): AppData => {
    switch(action.type) {
        case 'SET_DATA':
            return action.payload;
        case 'ENSURE_DAY_DATA': {
            const { date, dayData } = action.payload;
            if (state[date]) return state;
            const newState = { ...state };
            newState[date] = dayData;
            return newState;
        }
        case 'ADD_ITEM': {
            const { date, category } = action.payload;
            const newState = JSON.parse(JSON.stringify(state));
            if (!newState[date]) newState[date] = createEmptyDailyData();
            const newItem: EquipmentItem = {
                id: generateId(),
                qt: '', contract: '', serial: '', photos: []
            };
            newState[date][category].push(newItem);
            return newState;
        }
        case 'UPDATE_ITEM': {
            const { date, category, item } = action.payload;
            const newState = JSON.parse(JSON.stringify(state));
            const dayData = newState[date]?.[category];
            if (!dayData) return state;
            const itemIndex = dayData.findIndex((i: EquipmentItem) => i.id === item.id);
            if (itemIndex > -1) dayData[itemIndex] = item;
            else dayData.push(item);
            return newState;
        }
        case 'DELETE_ITEMS': {
            const { date, category, itemIds } = action.payload;
            const newState = JSON.parse(JSON.stringify(state));
            const dayData = newState[date]?.[category];
            if (!dayData) return state;
            newState[date][category] = dayData.filter((item: EquipmentItem) => !itemIds.includes(item.id));
            if (newState[date][category].length === 0) {
                 newState[date][category].push({ id: generateId(), qt: '', contract: '', serial: '', photos: [] });
            }
            return newState;
        }
        case 'CLEAR_ALL_DATA':
            return {};
        default:
            return state;
    }
}

const isItemActive = (item: EquipmentItem): boolean => {
    return (item.qt && item.qt.trim() !== '') || (item.contract && item.contract.trim() !== '') || (item.serial && item.serial.trim() !== '') || item.photos.length > 0;
};

// --- ERROR BOUNDARY ---

interface ErrorBoundaryProps { children?: React.ReactNode; }
interface ErrorBoundaryState { hasError: boolean; error: Error | null; }

class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: Error) { return { hasError: true, error }; }
  render() {
    if (this.state.hasError) {
      return (
        <div className="p-8 text-center">
          <h1 className="text-2xl font-bold text-red-600 mb-4">Erro inesperado</h1>
          <button onClick={() => window.location.reload()} className="px-4 py-2 bg-blue-500 text-white rounded">Recarregar</button>
        </div>
      )
    }
    return this.props.children;
  }
}

// --- MAIN APP ---

const AppContent = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [appData, dispatch] = useReducer(dataReducer, {});
  const [history, setHistory] = useState<AppData[]>([]);
  const [isRestoring, setIsRestoring] = useState(false);
  const [galleryItem, setGalleryItem] = useState<EquipmentItem | null>(null);
  const [activeModal, setActiveModal] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<EquipmentCategory>(CATEGORIES[0]);
  const [isSearchActive, setIsSearchActive] = useState(false);
  const [confirmation, setConfirmation] = useState<{ message: string; onConfirm: () => void } | null>(null);
  const [cameraModalItem, setCameraModalItem] = useState<EquipmentItem | null>(null);
  const [isGlobalDeleteMode, setIsGlobalDeleteMode] = useState(false);
  const [selectedItems, setSelectedItems] = useState<Record<string, string[]>>({});
  
  const formattedDate = getFormattedDate(currentDate);

  const dispatchWithHistory = (action: Action) => {
    setHistory(prev => [appData, ...prev].slice(0, 10)); 
    dispatch(action);
  };

  useEffect(() => {
    const savedData = localStorage.getItem('equipmentData');
    if (savedData) dispatch({ type: 'SET_DATA', payload: JSON.parse(savedData) });
  }, []);

  useEffect(() => {
    if (!appData[formattedDate]) {
      dispatch({ type: 'ENSURE_DAY_DATA', payload: { date: formattedDate, dayData: createEmptyDailyData() } });
    }
  }, [appData, formattedDate]);

  useEffect(() => {
    if (!isRestoring) localStorage.setItem('equipmentData', JSON.stringify(appData));
  }, [appData, isRestoring]);

  const currentDayData: DailyData = appData[formattedDate] || createEmptyDailyData();

  const handleAddItem = () => {
    if (!activeCategory) return;
    const items = currentDayData[activeCategory] || [];
    const lastItem = items[items.length - 1];
    if (!lastItem || isItemActive(lastItem)) {
      dispatchWithHistory({ type: 'ADD_ITEM', payload: { date: formattedDate, category: activeCategory } });
    }
  };

  const handleUpdateItem = (category: EquipmentCategory, item: EquipmentItem) => dispatchWithHistory({ type: 'UPDATE_ITEM', payload: { date: formattedDate, category, item } });

  const handleUndo = () => {
    if (history.length > 0) {
      const previousState = history[0];
      setHistory(history.slice(1));
      setIsRestoring(true);
      dispatch({ type: 'SET_DATA', payload: previousState });
    }
  }

  const handleToggleDeleteMode = () => {
    setIsGlobalDeleteMode(prev => !prev);
    setSelectedItems({}); 
  };

  const handleConfirmGlobalDelete = () => {
      const totalSelected = Object.values(selectedItems).reduce<number>((sum, ids: string[]) => sum + ids.length, 0);
      if (totalSelected > 0) {
        setConfirmation({
            message: `Apagar ${totalSelected} item(s)?`,
            onConfirm: () => {
                Object.entries(selectedItems).forEach(([cat, ids]: [string, string[]]) => {
                    if (ids.length > 0) dispatchWithHistory({ type: 'DELETE_ITEMS', payload: { date: formattedDate, category: cat as EquipmentCategory, itemIds: ids } });
                });
                handleToggleDeleteMode(); 
            }
        });
      }
  };

  return (
    // White/Milky Gloss Gradient Background
    <div className="min-h-screen bg-gradient-to-b from-white via-slate-50 to-slate-100 text-slate-700 font-sans pb-32">
      <SideMenu isOpen={isMenuOpen} onClose={() => setIsMenuOpen(false)} onMenuClick={(m) => { setActiveModal(m); setIsMenuOpen(false); }}/>
      
      <header className="sticky top-0 z-30 bg-white/40 backdrop-blur-xl pt-4 pb-2 px-4 relative overflow-hidden shadow-sm">
        {/* Watermark Text - Positioned lower and centered behind elements */}
        <div className="absolute top-6 inset-x-0 flex items-center justify-center pointer-events-none z-0 opacity-10">
             <span className="text-4xl font-black text-slate-800 uppercase tracking-widest whitespace-nowrap transform scale-150">EQUIPAMENTOS</span>
        </div>

        <div className="container mx-auto relative z-10">
            <div className="flex justify-between items-center mb-2">
                <button onClick={() => setIsMenuOpen(true)} className="active:scale-95 transition-transform drop-shadow-xl">
                    <CustomMenuIcon className="w-14 h-14" />
                </button>

                <div className="flex items-center gap-2">
                    {/* Buttons w-10 h-10 */}
                    <ActionButton onClick={handleAddItem}><IconPlus className="w-5 h-5" /></ActionButton>
                    <ActionButton onClick={handleToggleDeleteMode} isDanger={isGlobalDeleteMode}><IconMinus className="w-5 h-5" /></ActionButton>
                    {isGlobalDeleteMode && Object.values(selectedItems).reduce<number>((acc, items: string[]) => acc + items.length, 0) > 0 && (
                    <ActionButton onClick={handleConfirmGlobalDelete} isDanger={true}><IconTrash className="w-5 h-5" /></ActionButton>
                    )}
                    <ActionButton onClick={handleUndo}><IconUndo className="w-5 h-5" /></ActionButton>
                    <ActionButton onClick={() => setIsSearchActive(!isSearchActive)}><IconSearch className="w-5 h-5" /></ActionButton>
                </div>
            </div>

            <div className="text-center mt-2">
                <div className="inline-block px-6 py-1 rounded-full bg-white/40 border border-white/50 backdrop-blur-md shadow-sm">
                    <div className="text-lg font-extrabold text-slate-700 tracking-tight drop-shadow-sm">
                        {currentDate.toLocaleDateString('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' })}
                    </div>
                </div>
            </div>
        </div>
      </header>

      <main className="container mx-auto p-3 space-y-5">
        {CATEGORIES.map(category => (
            <EquipmentSection 
                key={`${formattedDate}-${category}`} 
                category={category} 
                items={currentDayData[category] || []}
                onUpdateItem={(item: EquipmentItem) => handleUpdateItem(category, item)}
                onViewGallery={(item: EquipmentItem) => setGalleryItem(item)}
                isDeleteMode={isGlobalDeleteMode}
                selectedItems={selectedItems[category] || []}
                onToggleSelect={(id: string) => setSelectedItems(prev => ({ ...prev, [category]: prev[category]?.includes(id) ? prev[category].filter(i => i !== id) : [...(prev[category]||[]), id] }))}
                isActive={category === activeCategory}
                onActivate={() => setActiveCategory(category)}
                onOpenCamera={(item: EquipmentItem) => setCameraModalItem(item)}
            />
        ))}
      </main>

      <SummaryFooter data={currentDayData} allData={appData} currentDate={formattedDate} />
            
      {galleryItem && <PhotoGalleryModal item={galleryItem} onClose={() => setGalleryItem(null)} onUpdatePhotos={(photos: string[]) => {
        const cat = Object.keys(currentDayData).find(k => currentDayData[k as EquipmentCategory].some(i => i.id === galleryItem.id)) as EquipmentCategory;
        if(cat) {
            const updated = { ...galleryItem, photos };
            handleUpdateItem(cat, updated);
            setGalleryItem(updated);
        }
      }} setConfirmation={setConfirmation} />}
      
      {cameraModalItem && <CameraModal onClose={() => setCameraModalItem(null)} onCapture={(photo: string, code: string) => {
           const cat = Object.keys(currentDayData).find(k => currentDayData[k as EquipmentCategory].some(i => i.id === cameraModalItem.id)) as EquipmentCategory;
           if (cat) {
               const updated = { ...cameraModalItem };
               if (photo) updated.photos = [...updated.photos, photo];
               if (code) updated.serial = code;
               handleUpdateItem(cat, updated);
           }
           setCameraModalItem(null);
      }} />}

      {activeModal === 'calendar' && <CalendarModal currentDate={currentDate} onClose={() => setActiveModal(null)} onDateSelect={(d: Date) => { setCurrentDate(d); setActiveModal(null); }}/>}
      {activeModal === 'save' && <DownloadModal appData={appData} currentDate={currentDate} onClose={() => setActiveModal(null)} />}
      {activeModal === 'export' && <ShareModal appData={appData} currentDate={currentDate} onClose={() => setActiveModal(null)} />}
      {activeModal === 'settings' && <SettingsModal onClose={() => setActiveModal(null)} onClearData={() => setConfirmation({ message: "Apagar tudo permanentemente?", onConfirm: () => { dispatchWithHistory({ type: 'CLEAR_ALL_DATA' }); setActiveModal(null); } })}/>}
      {activeModal === 'about' && <AboutModal onClose={() => setActiveModal(null)} onShareClick={() => setActiveModal('shareApp')}/>}
      {activeModal === 'shareApp' && <ShareModal appData={appData} currentDate={currentDate} isSharingApp onClose={() => setActiveModal(null)} />}
      {isSearchActive && <SearchModal onClose={() => setIsSearchActive(false)} appData={appData} onSelect={(res: any) => { 
          const [y, m, d] = res.date.split('-'); 
          setCurrentDate(new Date(y, m-1, d)); 
          setIsSearchActive(false); 
      }} />}
      {confirmation && <ConfirmationModal message={confirmation.message} onConfirm={() => { confirmation.onConfirm(); setConfirmation(null); }} onCancel={() => setConfirmation(null)} />}
    </div>
  );
};

const App = () => (<ErrorBoundary><AppContent /></ErrorBoundary>)
export default App;

// --- COMPONENTS ---

const ActionButton = ({ children, onClick, isPrimary, isDanger }: any) => (
    <button 
        onClick={onClick} 
        className={`w-10 h-10 rounded-full flex items-center justify-center transition-all active:shadow-inner active:translate-y-0.5 shadow-md border ${
            isPrimary ? 'bg-cyan-500 border-cyan-600 text-white' : 
            isDanger ? 'bg-red-50 border-red-100 text-red-500' :
            'bg-white/80 border-white/60 text-slate-600 hover:bg-white'
        }`}
    >
        {children}
    </button>
);

const EquipmentSection = ({ category, items, onUpdateItem, onViewGallery, isDeleteMode, selectedItems, onToggleSelect, isActive, onActivate, onOpenCamera }: any) => (
    <div onClick={onActivate}>
        <h2 className="text-lg font-bold text-slate-700 drop-shadow-sm shadow-white uppercase tracking-widest mb-2 ml-2">{category}</h2>
        <section className={`p-2 bg-white/40 backdrop-blur-lg border-t border-l border-white/60 border-b border-r border-white/20 rounded-xl shadow-lg transition-all duration-300 ${isActive ? 'ring-1 ring-white/60 scale-[1.01]' : ''}`}>
            <div className="space-y-2">
                {items.map((item: any) => (
                    <EquipmentRow 
                        key={item.id} item={item} onUpdate={onUpdateItem} isDeleteMode={isDeleteMode}
                        isSelected={selectedItems.includes(item.id)} onToggleSelect={() => onToggleSelect(item.id)} 
                        onViewGallery={() => onViewGallery(item)} onOpenCamera={() => onOpenCamera(item)}
                    />
                ))}
            </div>
        </section>
    </div>
);

const EquipmentRow = ({ item, onUpdate, isDeleteMode, isSelected, onToggleSelect, onViewGallery, onOpenCamera }: any) => {
    const handleChange = (field: string, value: string) => onUpdate({ ...item, [field]: value });
    const copy = (text: string) => navigator.clipboard.writeText(text);
    
    return (
        <div className={`flex items-center gap-0.5 p-1 rounded-lg transition-all ${isSelected ? 'bg-red-500/10 border border-red-200' : 'bg-white/20'}`}>
            {isDeleteMode && <input type="checkbox" checked={isSelected} onChange={onToggleSelect} className="form-checkbox h-4 w-4 rounded text-cyan-600 mr-1"/>}
            <div className="flex flex-1 items-center gap-0.5 min-w-0">
                {/* QT: Very small width */}
                <div className="w-8 flex-shrink-0">
                     <InputWithLabel placeholder="QT" type="number" value={item.qt} 
                        onChange={(e: any) => { if (e.target.value === '' || /^\d{1,2}$/.test(e.target.value)) handleChange('qt', e.target.value); }} 
                    />
                </div>
                {/* Serial (60%) & Contract (40%) */}
                <div className="flex-1 flex gap-0.5 min-w-0">
                     <div className="flex-[2] min-w-0 relative">
                        <InputWithLabel placeholder="Contrato" value={item.contract} onChange={(e: any) => handleChange('contract', e.target.value)} maxLength={10} onCopy={() => copy(item.contract)} />
                     </div>
                     <div className="flex-[3] min-w-0 relative">
                        <InputWithLabel placeholder="Serial" value={item.serial} onChange={(e: any) => handleChange('serial', e.target.value)} maxLength={20} onCopy={() => copy(item.serial)} />
                     </div>
                </div>
                {/* Buttons */}
                <div className="flex-shrink-0 flex gap-0.5 ml-0.5">
                    <button onClick={onOpenCamera} className="w-7 h-7 flex items-center justify-center bg-white rounded-md active:scale-95 text-gray-500 shadow-sm"><IconCamera className="w-3.5 h-3.5"/></button>
                    <button onClick={onViewGallery} className="relative w-7 h-7 flex items-center justify-center bg-white rounded-md active:scale-95 text-gray-500 shadow-sm" disabled={item.photos.length === 0}>
                        <IconGallery className="w-3.5 h-3.5"/>
                        {item.photos.length > 0 && <span className="absolute -top-1 -right-1 bg-cyan-500 text-white text-[8px] w-3 h-3 flex items-center justify-center rounded-full">{item.photos.length}</span>}
                    </button>
                </div>
            </div>
        </div>
    );
}

// Input: Carved Glass, Tiny Text for Mobile, Clipboard Icon Restored
const InputWithLabel = ({ placeholder, value, onChange, type = "text", maxLength, onCopy }: any) => (
    <div className="relative group w-full h-full">
        <input
            type={type} value={value} onChange={onChange} placeholder={placeholder} maxLength={maxLength}
            className="w-full h-8 bg-white/60 shadow-[inset_0_1px_2px_rgba(0,0,0,0.05)] border border-white/40 rounded-md px-0 py-1 text-[10px] font-medium text-slate-700 focus:outline-none focus:ring-1 focus:ring-purple-400 focus:bg-white placeholder-gray-500 transition-all text-center compact-input"
        />
        {onCopy && value && (
            <button onClick={onCopy} className="absolute right-0 top-0 h-full px-1 flex items-center justify-center opacity-50 hover:opacity-100 z-10">
                <IconClipboard className="w-2.5 h-2.5 text-slate-600" />
            </button>
        )}
    </div>
);

const SummaryFooter = ({ data, allData, currentDate }: any) => {
    const calc = (items: any[]) => items.reduce((acc, i) => isItemActive(i) ? acc + (parseInt(i.qt)||1) : acc, 0);
    const daily = Object.values(data).reduce((acc: number, items: any) => acc + calc(items as any[]), 0);
    const monthly = useMemo(() => {
        const [cy, cm] = currentDate.split('-');
        let t = 0;
        Object.entries(allData).forEach(([d, dd]: any) => { if(d.startsWith(`${cy}-${cm}`)) Object.values(dd).forEach((i: any) => t += calc(i)); });
        return t;
    }, [allData, currentDate]);

    return (
        <footer className="fixed bottom-0 left-0 w-full bg-white/40 backdrop-blur-xl border-t border-white/50 p-3 z-40 pb-safe">
            <div className="flex overflow-x-auto gap-3 pb-2 hide-scrollbar snap-x">
                {CATEGORIES.map(cat => (
                    <div key={cat} className="flex-shrink-0 bg-white/60 border border-white/60 rounded-xl px-3 py-1 min-w-[90px] flex flex-col items-center shadow-sm">
                        <span className="text-[8px] font-bold text-slate-600 uppercase mb-0.5">{cat}</span>
                        <span className="text-lg font-black text-slate-800">{calc(data[cat]||[])}</span>
                    </div>
                ))}
                <div className="flex-shrink-0 bg-purple-50/80 border border-purple-100 rounded-xl px-3 py-1 min-w-[100px] flex flex-col items-center shadow-sm">
                    <span className="text-[8px] font-bold text-purple-600 uppercase mb-0.5">TOTAL DIA</span>
                    <span className="text-lg font-black text-purple-800">{daily}</span>
                </div>
                <div className="flex-shrink-0 bg-pink-50/80 border border-pink-100 rounded-xl px-3 py-1 min-w-[100px] flex flex-col items-center shadow-sm">
                    <span className="text-[8px] font-bold text-pink-700 uppercase mb-0.5">SOMA TOTAL</span>
                    <span className="text-lg font-black text-pink-800">{monthly}</span>
                </div>
            </div>
        </footer>
    );
};

// --- MODALS (Milky/Ice Glass Theme) ---

const Modal = ({ children, onClose }: any) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/20 backdrop-blur-sm animate-fade-in" onClick={onClose}>
    <div className="bg-white/90 backdrop-blur-2xl rounded-2xl shadow-2xl w-full max-w-md overflow-hidden border border-white/50 animate-slide-in-up" onClick={e => e.stopPropagation()}>
      <div className="p-4 max-h-[80vh] overflow-y-auto relative">
        <button onClick={onClose} className="absolute top-3 right-3 bg-white/50 rounded-full p-1"><IconX className="w-5 h-5 text-slate-500"/></button>
        {children}
      </div>
    </div>
  </div>
);

const DownloadModal = ({ appData, currentDate, onClose }: any) => {
    const [range, setRange] = useState<'day' | 'month'>('day');
    
    const download = (type: 'word'|'excel') => {
        const { data, label } = getDataInRange(appData, currentDate, range);
        let content = '', mime = '', ext = '';
        
        if(type === 'word') {
            content = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word'><head><meta charset='utf-8'></head><body><h1>Relatório ${label}</h1>${CATEGORIES.map(cat => `<h3>${cat}</h3><ul>${(data[cat]||[]).filter(isItemActive).map((i:any)=>`<li>QT:${i.qt||1} C:${i.contract} S:${i.serial}</li>`).join('')}</ul>`).join('')}</body></html>`;
            mime = 'application/msword'; ext = '.doc';
        } else {
            content = `<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"></head><body><table><thead><tr><th>Cat</th><th>QT</th><th>Contrato</th><th>Serial</th></tr></thead><tbody>${CATEGORIES.flatMap(cat => (data[cat]||[]).filter(isItemActive).map((i:any)=>`<tr><td>${cat}</td><td>${i.qt||1}</td><td>${i.contract}</td><td>${i.serial}</td></tr>`)).join('')}</tbody></table></body></html>`;
            mime = 'application/vnd.ms-excel'; ext = '.xls';
        }
        
        const a = document.createElement('a');
        a.href = URL.createObjectURL(new Blob(['\ufeff', content], { type: mime }));
        a.download = `equipamentos_${range}_${getFormattedDate(currentDate)}${ext}`;
        a.click();
    };
    
    return (
        <Modal onClose={onClose}>
            <h3 className="text-xl font-bold text-center mb-2 text-slate-700">Salvar Manualmente</h3>
            <div className="flex justify-center gap-2 mb-6">
                <button onClick={()=>setRange('day')} className={`px-3 py-1 rounded-lg text-sm font-bold border ${range === 'day' ? 'bg-cyan-500 text-white' : 'bg-slate-100 text-slate-600'}`}>Apenas Hoje</button>
                <button onClick={()=>setRange('month')} className={`px-3 py-1 rounded-lg text-sm font-bold border ${range === 'month' ? 'bg-cyan-500 text-white' : 'bg-slate-100 text-slate-600'}`}>Mês até Hoje</button>
            </div>
            <div className="grid grid-cols-2 gap-4">
                <button onClick={() => download('word')} className="flex flex-col items-center p-4 bg-blue-50 rounded-xl border border-blue-100"><IconFileWord className="w-10 h-10 text-blue-600 mb-2"/><span className="text-blue-800 font-bold">Word</span></button>
                <button onClick={() => download('excel')} className="flex flex-col items-center p-4 bg-green-50 rounded-xl border border-green-100"><IconFileExcel className="w-10 h-10 text-green-600 mb-2"/><span className="text-green-800 font-bold">Excel</span></button>
            </div>
        </Modal>
    );
};

const ShareModal = ({ appData, currentDate, onClose, isSharingApp }: any) => {
    const [range, setRange] = useState<'day' | 'month'>('day');
    
    const generateText = () => {
        if (isSharingApp) return `Baixe o App Controle de Equipamentos aqui: ${window.location.href}`;
        
        const { data, label } = getDataInRange(appData, currentDate, range);
        let txt = `*Relatório de Equipamentos - ${label}*\n\n`;
        
        let hasItems = false;
        CATEGORIES.forEach(cat => {
             const items = (data[cat] || []).filter(isItemActive);
             if (items.length > 0) {
                 hasItems = true;
                 txt += `*${cat}* (${items.reduce((acc:number, i:any) => acc + (parseInt(i.qt)||1), 0)})\n`;
                 items.forEach((i:any) => {
                     txt += `- QT:${i.qt||1} | C:${i.contract} | S:${i.serial}\n`;
                 });
                 txt += `\n`;
             }
        });
        if (!hasItems) txt += "Nenhum item registrado neste período.";
        return txt;
    };

    const open = (url: string) => window.open(url, '_blank');
    const txt = generateText();

    return (
        <Modal onClose={onClose}>
            <h3 className="text-xl font-bold text-center mb-2 text-slate-700">{isSharingApp ? 'Compartilhar App' : 'Exportar'}</h3>
            
            {!isSharingApp && (
                <div className="flex justify-center gap-2 mb-6">
                     <button onClick={()=>setRange('day')} className={`px-3 py-1 rounded-lg text-sm font-bold border ${range === 'day' ? 'bg-cyan-500 text-white' : 'bg-slate-100 text-slate-600'}`}>Apenas Hoje</button>
                     <button onClick={()=>setRange('month')} className={`px-3 py-1 rounded-lg text-sm font-bold border ${range === 'month' ? 'bg-cyan-500 text-white' : 'bg-slate-100 text-slate-600'}`}>Mês até Hoje</button>
                </div>
            )}

            <div className="flex justify-around">
                <button onClick={() => open(`https://wa.me/?text=${encodeURIComponent(txt)}`)} className="flex flex-col items-center"><IconWhatsapp className="w-10 h-10 text-green-500"/><span className="text-xs font-bold text-slate-600">WhatsApp</span></button>
                <button onClick={() => open(`https://t.me/share/url?url=${encodeURIComponent(window.location.href)}&text=${encodeURIComponent(txt)}`)} className="flex flex-col items-center"><IconTelegram className="w-10 h-10 text-blue-500"/><span className="text-xs font-bold text-slate-600">Telegram</span></button>
                <button onClick={() => open(`mailto:?subject=Relatório&body=${encodeURIComponent(txt)}`)} className="flex flex-col items-center"><IconEmail className="w-10 h-10 text-gray-500"/><span className="text-xs font-bold text-slate-600">E-mail</span></button>
            </div>
            <p className="text-xs text-slate-400 text-center mt-4">O relatório será colado no corpo da mensagem.</p>
        </Modal>
    );
};

const CameraModal = ({ onClose, onCapture }: any) => {
    useEffect(() => {
        const scanner = new (window as any).Html5QrcodeScanner("reader", { fps: 10, qrbox: 250 }, false);
        scanner.render((txt: string) => { scanner.clear(); onCapture('', txt); }, console.error);
        return () => { try { scanner.clear(); } catch(e){} };
    }, []);
    return (
        <div className="fixed inset-0 z-50 bg-black flex flex-col items-center justify-center">
            <div id="reader" className="w-full max-w-sm bg-white rounded-lg overflow-hidden"></div>
            <button onClick={onClose} className="mt-4 p-2 bg-white/20 rounded-full text-white"><IconX className="w-8 h-8"/></button>
        </div>
    );
};

const PhotoGalleryModal = ({ item, onClose, onUpdatePhotos, setConfirmation }: any) => {
    const ref = useRef<HTMLInputElement>(null);
    const [view, setView] = useState<number|null>(null);
    const add = (e: any) => {
        const f = e.target.files?.[0];
        if(f) { const r = new FileReader(); r.onload = (ev) => onUpdatePhotos([...item.photos, ev.target?.result]); r.readAsDataURL(f); }
    };
    return (
        <Modal onClose={onClose}>
            <h3 className="text-xl font-bold text-center mb-4 text-slate-700">Galeria</h3>
            <div className="grid grid-cols-3 gap-2 mb-4">
                {item.photos.map((p: string, i: number) => (
                    <img key={i} src={p} onClick={() => setView(i)} className="aspect-square rounded-lg object-cover shadow-sm cursor-pointer"/>
                ))}
                <button onClick={() => ref.current?.click()} className="aspect-square rounded-lg border-2 border-dashed border-cyan-300 flex items-center justify-center text-cyan-400"><IconPlus className="w-6 h-6"/></button>
            </div>
            <input type="file" accept="image/*" ref={ref} className="hidden" onChange={add} />
            {view !== null && (
                <div className="fixed inset-0 z-[60] bg-black/95 flex flex-col items-center justify-center p-4" onClick={() => setView(null)}>
                    <img src={item.photos[view]} className="max-w-full max-h-[80vh] rounded-lg mb-4" />
                    <button onClick={(e) => { e.stopPropagation(); setConfirmation({ message: "Excluir foto?", onConfirm: () => { onUpdatePhotos(item.photos.filter((_:any, i:number) => i !== view)); setView(null); }}); }} className="px-6 py-2 bg-red-500 text-white rounded-full font-bold">Excluir</button>
                </div>
            )}
        </Modal>
    );
};

const SettingsModal = ({ onClose, onClearData }: any) => (
    <Modal onClose={onClose}>
        <h3 className="text-xl font-bold text-center mb-4 text-slate-700">Configurações</h3>
        <button onClick={onClearData} className="w-full p-3 bg-red-50 text-red-600 rounded-xl font-bold border border-red-100 flex items-center justify-center gap-2"><IconTrash className="w-5 h-5"/> Limpar Tudo</button>
    </Modal>
);

const AboutModal = ({ onClose, onShareClick }: any) => (
    <Modal onClose={onClose}>
        <div className="text-center">
            <CustomMenuIcon className="w-20 h-20 mx-auto mb-2 drop-shadow-xl" />
            <h2 className="text-xl font-black text-slate-800">Controle de Equipamentos</h2>
            <p className="text-xs font-mono text-cyan-600 bg-cyan-50 inline-block px-2 py-1 rounded mb-4">V0.0.1b</p>
            <div className="bg-slate-50 rounded-lg p-3 mb-4 text-left text-sm text-slate-600 border border-slate-100"><p><b>Dono:</b> Leo Luz</p></div>
            <button onClick={onShareClick} className="w-full py-2 bg-cyan-500 text-white rounded-lg font-bold shadow-md">Compartilhar App</button>
        </div>
    </Modal>
);

const CalendarModal = ({ currentDate, onClose, onDateSelect }: any) => {
    const [d, setD] = useState(currentDate);
    const days = new Date(d.getFullYear(), d.getMonth()+1, 0).getDate();
    const start = new Date(d.getFullYear(), d.getMonth(), 1).getDay();
    return (
        <Modal onClose={onClose}>
            <div className="text-center">
                <div className="flex justify-between items-center mb-4">
                    <button onClick={() => setD(new Date(d.getFullYear(), d.getMonth()-1, 1))}><IconChevronLeft className="w-5 h-5 text-slate-500"/></button>
                    <span className="font-bold text-slate-700 capitalize">{d.toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' })}</span>
                    <button onClick={() => setD(new Date(d.getFullYear(), d.getMonth()+1, 1))}><IconChevronRight className="w-5 h-5 text-slate-500"/></button>
                </div>
                <div className="grid grid-cols-7 gap-1">
                    {Array.from({length: start}).map((_,i)=><div key={i}/>)}
                    {Array.from({length: days}).map((_,i)=>{
                        const x = new Date(d.getFullYear(), d.getMonth(), i+1);
                        const isSel = x.toDateString() === currentDate.toDateString();
                        return <button key={i} onClick={() => onDateSelect(x)} className={`h-8 w-8 rounded-full text-xs font-bold ${isSel ? 'bg-cyan-500 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{i+1}</button>
                    })}
                </div>
            </div>
        </Modal>
    )
};

const SearchModal = ({ onClose, appData, onSelect }: any) => {
    const [q, setQ] = useState('');
    const res = useMemo(() => {
        if(q.length<2) return [];
        const r: any[] = [];
        Object.entries(appData).forEach(([d, dd]: any) => Object.entries(dd).forEach(([c, items]: any) => (items as any[]).forEach(i => {
            if(i.serial.toLowerCase().includes(q.toLowerCase()) || i.contract.toLowerCase().includes(q.toLowerCase())) r.push({ date: d, category: c, item: i });
        })));
        return r;
    }, [q, appData]);
    return (
        <Modal onClose={onClose}>
            <h3 className="font-bold text-slate-700 mb-2">Buscar</h3>
            <input autoFocus value={q} onChange={e=>setQ(e.target.value)} className="w-full p-2 bg-slate-50 border rounded-lg mb-2 outline-none focus:ring-1 ring-cyan-400" placeholder="Serial/Contrato..."/>
            <div className="max-h-40 overflow-y-auto space-y-1">
                {res.map((r,i)=><button key={i} onClick={()=>onSelect(r)} className="w-full text-left p-2 bg-white border rounded-md text-xs hover:bg-cyan-50"><b>{r.category}</b> - {r.date}<br/>S: {r.item.serial}</button>)}
            </div>
        </Modal>
    );
};

const ConfirmationModal = ({ message, onConfirm, onCancel }: any) => (
    <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm">
        <div className="bg-white/95 p-6 rounded-xl shadow-2xl max-w-xs w-full">
            <p className="text-slate-700 mb-4 font-medium">{message}</p>
            <div className="flex justify-end gap-2">
                <button onClick={onCancel} className="px-3 py-1 text-slate-500 font-bold">Cancelar</button>
                <button onClick={onConfirm} className="px-3 py-1 bg-red-500 text-white rounded-lg font-bold">Confirmar</button>
            </div>
        </div>
    </div>
);